# site settings
title: Compiling Gibberish
subtitle: by Parth Shah
email: parth.c.shah@gmail.com
description: Welcome to my nook on the internet. This website showcases some interesting projects I've worked on in the past.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://parthshah.org
author: Parth Shah
street_address: 
city: Townsville
state: Queensland
zip_code: 4811
country: Australia
phone: +61 0481711597

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/profile.php?id=100076261054689
github_url: https://github.com/valvze
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/parth-shah-a041741b4/
pinterest_url:
slack_url:
twitter_url: 
youtube_url: https://www.youtube.com/channel/UCdcqOdNQKuq0FYH_6XETGyw

# build settings
markdown: kramdown

sass:
  style: compressed
